# Name: Makefile.windows
# Project: hid-data example
# Author: Christian Starkjohann
# Creation Date: 2008-04-11
# Tabsize: 4
# Copyright: (c) 2008 by OBJECTIVE DEVELOPMENT Software GmbH
# License: GNU GPL v2 (see License.txt), GNU GPL v3 or proprietary (CommercialLicense.txt)
# This Revision: $Id$

# You may use this file with
#   make -f Makefile.windows
# on Windows with MinGW instead of editing the main Makefile.

include Makefile

USBFLAGS=
USBLIBS=    -lhid -lsetupapi
EXE_SUFFIX= .exe
